lint & tests

diff --git a/.github/workflows/feature-push.yaml b/.github/workflows/feature-push.yaml
--- a/.github/workflows/feature-push.yaml
+++ b/.github/workflows/feature-push.yaml
@@ -44,9 +44,76 @@ jobs:
         uses: hadolint/hadolint-action@v2.0.0
         with:
           dockerfile: Dockerfile
-    ######################### LINTERS ###################################
 
-     
+    ######################### LINTERS ###################################
+  
+    test-terraform: 
+     name: running terraform tests
+     runs-on: ubuntu-latest
+     env:
+        WORKING_DIRECTORY: terraform
+  
+     steps:
+      - name: 'Use terraform 1.1.7'
+        uses: hashicorp/setup-terraform@v1
+        with:
+          terraform_version: 1.1.7
+
+      - name: 'Terraform fmt'
+        id: fmt
+        run: terraform fmt -check
+        continue-on-error: true
+        working-directory: ${{ env.WORKING_DIRECTORY }}    
+
+      # - name: Run tfsec with reviewdog output on the PR
+      #   uses: reviewdog/action-tfsec@master
+      #   with:
+      #     github_token: ${{ secrets.GITH_TOKEN }}
+      #     working_directory: ./terraform # Change working directory
+      #     level: info # Get more output from reviewdog
+      #     reporter: github-pr-review # Change reviewdog reporter
+      #     #filter_mode: nofilter # Check all files, not just the diff
+      #     fail_on_error: true # Fail action if errors are found
+      #     flags: -tee # Add debug flag to reviewdog
+      #     #tfsec_flags: "" # Optional
+  
+      - name: 'Terraform init'
+        id: init
+        run: terraform init 
+        working-directory: ${{ env.WORKING_DIRECTORY }}
+
+      - name: terraform validate
+        uses: robertdebock/terraform-action@1.1.2
+        with:
+          action: validate
+          directory: ${{ env.WORKING_DIRECTORY }} 
+
+      # - name: Terraform plan
+      #   id: plan
+      #   run: terraform plan -no-color
+      #   working-directory: ${{ env.WORKING_DIRECTORY }}
+
+
+      - name: Terraform Plan Status
+        if: steps.plan.outcome == 'failure'
+        run: exit 1 
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
     ######################### Create docker image ###################################
     # docker-build-and-push:
     #     name: build-docker-image
