new ver.1.3

diff --git a/.github/workflows/feature-push.yaml b/.github/workflows/feature-push.yaml
--- a/.github/workflows/feature-push.yaml
+++ b/.github/workflows/feature-push.yaml
@@ -55,111 +55,39 @@ jobs:
         continue-on-error: true
         working-directory: ${{ env.WORKING_DIRECTORY }}    
 
-      - name: Run tfsec with reviewdog output on the PR
-        uses: reviewdog/action-tfsec@master
-        with:
-          github_token: ${{ secrets.MY_GITHUB_TOKEN1 }}
-          working_directory: ${{ env.WORKING_DIRECTORY }} #./terraform # Change working directory
-          level: info # Get more output from reviewdog
-          reporter: github-pr-review # Change reviewdog reporter
-          #filter_mode: nofilter # Check all files, not just the diff
-          fail_on_error: true # Fail action if errors are found
-          flags: -tee # Add debug flag to reviewdog
-          #tfsec_flags: "" # Optional
+      # - name: Run tfsec with reviewdog output on the PR
+      #   uses: reviewdog/action-tfsec@master
+      #   with:
+      #     github_token: ${{ secrets.MY_GITHUB_TOKEN1 }}
+      #     working_directory: ${{ env.WORKING_DIRECTORY }} #./terraform # Change working directory
+      #     level: info # Get more output from reviewdog
+      #     reporter: github-pr-review # Change reviewdog reporter
+      #     #filter_mode: nofilter # Check all files, not just the diff
+      #     fail_on_error: true # Fail action if errors are found
+      #     flags: -tee # Add debug flag to reviewdog
+      #     #tfsec_flags: "" # Optional
   
-      - name: 'Terraform init'
-        id: init
-        run: terraform init 
-        working-directory: ${{ env.WORKING_DIRECTORY }}
+      # - name: 'Terraform init'
+      #   id: init
+      #   run: terraform init 
+      #   working-directory: ${{ env.WORKING_DIRECTORY }}
 
-      - name: terraform validate
-        uses: robertdebock/terraform-action@1.1.2
-        with:
-          action: validate
-          directory: ${{ env.WORKING_DIRECTORY }} 
+      # - name: terraform validate
+      #   uses: robertdebock/terraform-action@1.1.2
+      #   with:
+      #     action: validate
+      #     directory: ${{ env.WORKING_DIRECTORY }} 
 
-      - name: Terraform plan
-        id: plan
-        run: terraform plan -no-color
-        working-directory: ${{ env.WORKING_DIRECTORY }}
+      # - name: Terraform plan
+      #   id: plan
+      #   run: terraform plan -no-color
+      #   working-directory: ${{ env.WORKING_DIRECTORY }}
 
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1 
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1 
     ######################### LINTERS & TESTS ###################################
-
-
-    ######################### Create docker image ########## Здесь правильной!! Брать отсюда!! #########################
-   
-    # build-and-push-image:
-    #     runs-on: ubuntu-latest
-    #     permissions:
-    #       contents: read
-    #       packages: write
-
-    #     steps:
-    #       - name: Checkout repository
-    #         uses: actions/checkout@v3
-
-    #       - name: Log in to the Container registry
-    #         uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
-    #         with:
-    #           registry: ${{ env.REGISTRY }}
-    #           username: ${{ github.actor }}
-    #           password: ${{ secrets.GITHUB_TOKEN }}
-
-    #       - name: Extract metadata (tags, labels) for Docker
-    #         id: meta
-    #         uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
-    #         with:
-    #           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
-
-    #       - name: Build and push Docker image
-    #         uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
-    #         with:
-    #           context: .
-    #           push: true
-    #           tags: ${{ steps.meta.outputs.tags }}
-    #           labels: ${{ steps.meta.outputs.labels }}
-
-
-######################### Create docker image ########## Здесь правильной!! Брать отсюда!! #########################
-
-
-
-    ######################### Create docker image ###################################
-    # docker-build-and-push:
-    #     name: build-docker-image
-    #     runs-on: ubuntu-latest  
-    #     # needs: 
-    #     #   - lint-dockerfile
-    #     steps:      
-    #     - name: Checkout repository
-    #       uses: actions/checkout@v3
-
-    #     - name: Login to GitHub Container Registry
-    #       uses: docker/login-action@v1
-    #       with:
-    #         registry: ghcr.io
-    #         username: ${{ github.actor }}
-    #         password: ${{ secrets.MY_GITHUB_TOKEN1 }}
-        
-    #     - name: Build & Push to GitHub Package 
-    #       uses: opspresso/action-docker@master  
-    #       with:
-    #         args: --docker
-    #       env:
-    #         PASSWORD: ${{ secrets.MY_GITHUB_TOKEN1 }}
-    #         REGISTRY: "docker.pkg.github.com"
-    #         TAG_NAME: "feature-v5.0.0-full"
-    #         #DOCKERFILE: ./Dockerfile
-    #         DOCKER_BUILD_ARGS: --build-arg BUILD_TYPE=full   #min
-    #         IMAGE_NAME: openmeetings-dp
-    ######################### Create docker image ###################################
-
-
-# https://localhost:5443/openmeetings/install?2  попробовать
 
 
   ######################### Create pull request ###################################
